.catalog:
  name: "ECR Key Rotator"
  version: 0.0.1
  description: "Updates credentials for ECR in Rancher"
  questions:
    - variable: "aws_access_key_id"
      label: "AWS Access Key ID"
      description: "AWS API Access Key to use for obtaining ECR credentials. Not required if using IAM roles."
      required: false
      type: "string"
    - variable: "aws_secret_access_key"
      label: "AWS Secret Access Key"
      description: "AWS API Secret Key to use for obtaining ECR credentials. Not required if using IAM roles."
      required: false
      type: "string"
    - variable: "aws_region"
      label: "AWS Region"
      description: "AWS Region that hosts the ECR"
      default: us-east-1
      required: true
      type: "string"
    - variable: "rancher_access_key"
      label: "Rancher Access Key"
      description: "Rancher Access Key Created in API Keys"
      required: false
      type: "string"
    - variable: "rancher_secret_key"
      label: "Rancher Secret Key"
      description: "Rancher Access Key Created in API Keys"
      required: false
      type: "string"
    - variable: "rancher_url"
      label: "Rancher URL"
      description: "Rancher URL for API access"
      required: false
      type: "string"
    - variable: "project_id"
      label: "Project ID"
      description: "Rancher Environment Project ID (See URL above for ID Value"
      required: false
      type: "string"
    - variable: "ecr_registry"
      label: "ECR Registry URL"
      description: "AWS ECR Registry Base URL"
      default: 571978632649.dkr.ecr.us-east-1.amazonaws.com
      required: true
      type: "string"
    - variable: "sleep_time"
      label: "Sleep Time"
      description: "Time to Sleep between Runs"
      default: 36000
      required: true
      type: "string"
ecr-updater:
  scale: 1
