DockerCleanup:
  image: 571978632649.dkr.ecr.us-east-1.amazonaws.com/appriss-devops-services/docker_clean:latest
  stdin_open: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock:rw
  - /tmp:/tmp:rw
  - /var/log:/home/var/log:rw
  tty: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
