version: '2'
catalog:
  name: DockerCleanup # Name of the versioned template of the Catalog Entry
  version: 0.0.1 # Version of the versioned template of the Catalog Entry
  description: Docker Cleanup for Version Control # Description of the versioned template of the Catalog Entry
  minimum_rancher_version: 0.0.1 # The minimum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  maximum_rancher_version: >=1.0.0 # The maximum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  upgrade_from: # The previous versions that this template can be upgraded from
  questions: #Used to request user input for configuration options

services:
  DockerCleanup:
    start_on_create: true

