jenkins-primary:
  image: biodev.ece.ucsb.edu:5000/cbi-jenkins2
  ports:
    - "${PORT}:8080"
  environment:
    - TZ=America/Los_Angeles
  labels:
    io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: visible=internet
  volumes_from:
    - jenkins-plugins
    - jenkins-datavolume
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  entrypoint: /usr/share/jenkins/rancher/jenkins.sh

jenkins-plugins:
  image: rancher/jenkins-plugins:v0.1.1
jenkins-datavolume:
  image: "busybox"
  volumes:
    - ${volume_work}:/var/jenkins_home
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
