.catalog:
  name: "ECR Key Rotator"
  version: 0.0.2
  description: "Updates credentials for ECR in Rancher"
services:
  RancherAdminService-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: RancherAdminService-v2
        source_port: 443
        target_port: 443
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  RancherAdminService-v2:
    scale: 1
    start_on_create: true
