version: '2'
catalog:
  name: Jenkins
  version: 3
  description: |
    Jenkins CI management server.
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should Jenkins listen on?"
    default: 8080
    required: true
  - variable: "volume_work"
    description: "Work volume to save jenkins data"
    label: "Work volume:"
    required: true
    #default: "/var/lib/docker/jenkins-ci"
    default: "/var/jenkins_home"
    type: "string"
  - variable: "plugins"
    type: "multiline"
    label: "List of Plugins"
    description: |
      List of plugins in the format <plugin_name>[:<version>]
      one entry per line.
    default: |
      amazon-ecr
      configurationslicing
      credentials
      docker-build-publish
      bitbucket
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      mailer
      mercurial
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      ssh-agent
      swarm

jenkins-primary:
  metadata:
    plugins: |
      ${plugins}
